spring:
  application:
    name: employee-service
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://localhost:8888/employee-service-config
server:
  port: 8082